apiVersion: v1
kind: ConfigMap
metadata:
  name: sample-map-config
data:
  APP_ENV: "production"
  APP_DEBUG: "false"
  DB_CONNECTION: "mysql"
  DB_HOST: "sample-app-mysql"
  DB_PORT: "3306"
  DB_DATABASE: "app_database"
